services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: edu_portal_app
    ports:
      - "${PORT:-8080}:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
